// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create-repo-not-existed', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create-repo-not-existed', async function() {
    await driver.get("https://github.com/")
    await driver.manage().window().setRect({ width: 1440, height: 828 })
    await driver.findElement(By.linkText("Create repository")).click()
  })
})
